import { writeFile, readFile } from "node:fs/promises";
import {
  profile,
  experience,
  education,
  publications,
  projects,
  industryProjects,
} from "../data/portfolio.mjs";

const esc = (value) =>
  String(value).replace(
    /[&<>"']/g,
    (c) =>
      ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[
        c
      ],
  );
const link = ([label, href], cls = "") =>
  `<a${cls ? ` class="${cls}"` : ""} href="${esc(href)}">${esc(label)}<span aria-hidden="true"> ↗</span></a>`;
const links = (items) => items.map((item) => link(item)).join("");
const image = (file, alt, cls = "") =>
  `<img class="${cls}" src="assets/img/${file.replace(/\.png$/, ".webp")}" alt="${esc(alt)}" loading="lazy" decoding="async" width="800" height="480">`;
const sectionHead = (n, title, detail = "") =>
  `<div class="section-heading"><div><p class="eyebrow">${n}</p><h2>${title}</h2></div>${detail}</div>`;
const navigation = (page) =>
  `<a class="skip-link" href="#main">Skip to content</a><nav class="navigation" aria-label="Primary navigation"><div class="nav-inner"><a class="brand" href="index.html" aria-label="Byeong Gwon Lee — Home"><span class="brand-mark" aria-hidden="true">bgl<span>.</span></span><span>Byeong Gwon Lee</span></a><button class="menu-toggle" aria-expanded="false" aria-controls="nav-links" hidden>Menu <span aria-hidden="true">+</span></button><div id="nav-links" class="nav-links">${[
    ["Research", "index.html"],
    ["Projects", "projects.html"],
    ["Publications", "publications.html"],
    ["About", "about.html"],
  ]
    .map(
      ([label, href]) =>
        `<a href="${href}"${page === href ? ' aria-current="page"' : ""}>${label}</a>`,
    )
    .join(
      "",
    )}<a class="nav-contact" href="#contact">Get in touch <span aria-hidden="true">↗</span></a></div></div></nav>`;
const contact = `<section class="contact" id="contact"><div><p class="eyebrow">LET’S CONNECT</p><h2>Better geometry.<br>New perspectives.</h2><p>For research discussions and collaborations in 3D vision.</p></div><div class="contact-details"><a class="email" href="mailto:${profile.email}">${profile.email} <span aria-hidden="true">↗</span></a><div class="text-links">${links(profile.links)}</div></div></section>`;
function page(file, title, description, body, extra = "") {
  return `<!doctype html>\n<!-- Generated by scripts/build.mjs. Edit data/portfolio.mjs or the build template. -->\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)} — ${profile.name}</title><meta name="description" content="${esc(description)}"><meta property="og:title" content="${esc(title)} — ${profile.name}"><meta property="og:description" content="${esc(description)}"><meta property="og:type" content="website"><meta property="og:image" content="https://lbg030.github.io/assets/img/og-preview.png"><link rel="icon" href="assets/img/favicon.png"><link rel="stylesheet" href="styles.css"><script type="module" src="assets/js/site.js"></script>${extra}</head><body>${navigation(file)}<main id="main">${body}${contact}</main><footer class="footer"><span>© ${new Date().getFullYear()} ${profile.name}</span><span>3D vision. Grounded in geometry.</span><a href="#main">Back to top ↑</a></footer></body></html>\n`;
}
function publication(p, compact = false) {
  const review = p.status === "Under Review";
  return `<article id="${p.id}" class="publication${review ? " review" : ""}${compact ? " compact" : ""}">${p.image ? `<a class="publication-image" href="assets/img/${p.image}" aria-label="View figure: ${esc(p.title)}">${image(p.image, `Research overview: ${p.title}`)}</a>` : `<div class="paper-index" aria-hidden="true">${p.id === "m2depth" ? "M²<br>Depth" : "M²<br>SLAM"}</div>`}<div class="publication-body"><div class="publication-meta"><span>${esc(p.venue)}${p.venue.includes(p.year) ? "" : ` · ${p.year}`}</span><span class="status ${review ? "status-review" : ""}">${p.status}</span></div><h3>${esc(p.title)}</h3><p class="author-role">${p.role}</p>${!compact && p.authors ? `<p class="authors">${esc(p.authors)}</p>` : ""}<p>${esc(p.summary)}</p>${p.links.length ? `<div class="text-links">${links(p.links)}</div>` : ""}</div></article>`;
}
function project(p, detail = false) {
  const heading = detail ? "h2" : "h3";
  return `<article class="project" id="${p.id}"><a class="project-image" href="${detail ? `assets/img/${p.image}` : `projects.html#${p.id}`}" aria-label="${detail ? "View image for" : "Read case study"}: ${esc(p.fullTitle)}">${image(p.image, p.alt)}</a><div class="project-body"><p class="eyebrow">${esc(p.organization)} · ${p.date}</p><${heading}>${esc(p.title)}</${heading}><p class="project-tags">${p.tags}</p>${detail ? `<p>${esc(p.fullTitle)}</p><dl class="case-study">${["problem", "approach", "contribution", "result"].map((key) => `<div><dt>${key}</dt><dd>${esc(p[key])}</dd></div>`).join("")}</dl><div class="text-links">${links(p.links)}</div>` : `<p>${esc(p.approach)}</p>${link(["Explore the project", `projects.html#${p.id}`], "arrow-link")}`}</div></article>`;
}
const experienceSection = `<section id="experience">${sectionHead("EXPERIENCE", "Research in practice.")}<ol class="timeline">${experience.map((e, i) => `<li${i === 0 ? ' class="current"' : ""}><p class="timeline-date">${e.date}</p><div><h3>${e.organization}${i === 0 ? '<span class="current-label">Current</span>' : ""}</h3><p class="timeline-role">${e.role}</p>${e.description ? `<p>${e.description}</p>` : ""}</div></li>`).join("")}</ol></section>`;
const educationSection = `<section id="education">${sectionHead("EDUCATION", "A foundation in vision.")}<ol class="timeline">${education.map((e) => `<li><p class="timeline-date">${e.date}</p><div><h3>${e.organization}</h3><p class="timeline-role">${e.degree}</p>${e.description ? `<p>${e.description}</p><p class="muted">${e.thesis}</p>` : ""}</div></li>`).join("")}</ol></section>`;
const focus = `<section id="focus">${sectionHead("01 / RESEARCH FOCUS", "Understanding the world in 3D.", "<p>Connecting learned visual priors with<br>the structure of multi-view geometry.</p>")}<div class="focus-grid"><article><span class="focus-symbol" aria-hidden="true">⌘</span><h3>Geometry & depth</h3><p>Multi-view stereo and monocular depth priors for complete, consistent scene geometry.</p></article><article><span class="focus-symbol" aria-hidden="true">◎</span><h3>Mapping & localization</h3><p>SLAM and camera pose estimation connecting image sequences to spatial understanding.</p></article><article><span class="focus-symbol" aria-hidden="true">⠿</span><h3>Neural reconstruction</h3><p>3D Gaussian Splatting and view selection for detailed, online scene reconstruction.</p></article></div></section>`;
const scene = `<figure class="reconstruction" aria-labelledby="scene-caption" aria-describedby="scene-description"><p id="scene-description" class="visually-hidden">Illustrative 3D reconstruction: building surfaces are represented by a point cloud, surrounded by camera frustums along a curved capture trajectory. The density slider changes sparse samples into denser surface coverage. This is an illustration, not an experimental result.</p><div class="scene-top"><span class="eyebrow">GEOMETRY LAB / 01</span><span class="scene-label">Illustrative reconstruction</span></div><div id="scene-viewport"><img class="scene-fallback" src="assets/img/reconstruction.svg" width="660" height="470" alt="Illustrative building point cloud with camera frustums following a curved capture trajectory"></div><div class="scene-controls" hidden><label for="density">Sparse <input type="range" id="density" min="0" max="100" value="72" aria-label="Reconstruction density"> Dense</label><button type="button" id="rotate" aria-pressed="false">Rotate view</button></div><figcaption id="scene-caption"><span><i class="legend-dot" aria-hidden="true"></i> Scene geometry</span><span><i class="legend-line" aria-hidden="true"></i> Camera trajectory</span></figcaption></figure>`;
const featuredPaper = publications.find((p) => p.id === "ijcai");
const featuredProject = projects.find((p) => p.id === "drone");
const heroEvidence = `<div class="hero-evidence" aria-label="Selected research"><a href="publications.html#${featuredPaper.id}"><span class="evidence-label">${esc(featuredPaper.venue)} · ${featuredPaper.role}</span><strong>Online 3D Gaussian Splatting</strong><span aria-hidden="true">↗</span></a><a href="projects.html#${featuredProject.id}"><span class="evidence-label">${esc(featuredProject.organization)} · Research project</span><strong>Drone-based 3D reconstruction</strong><span aria-hidden="true">↗</span></a></div>`;
const hero = `<header class="hero"><div class="hero-copy"><p class="eyebrow">BYEONG GWON LEE <span class="korean-name" lang="ko">/ 이병권</span></p><h1>3D Computer<br>Vision <span>Researcher</span></h1><p class="hero-fields">${profile.fields}</p><p class="hero-description">Turning images into geometry.<br>I work on depth, mapping, and 3D reconstruction.</p><p class="affiliation"><span class="live-dot" aria-hidden="true"></span><strong>${experience[0].organization}</strong><span>${experience[0].role} · ${experience[0].date}</span></p>${heroEvidence}<div class="hero-actions">${link(["Explore research", "#publications"], "button primary")}${link(["CV (PDF)", "cv/cv.pdf"], "button")}</div><div class="hero-profiles">${links([["Email", `mailto:${profile.email}`], ...profile.links.slice(1)])}</div></div>${scene}</header>`;
const pipeline = `<section class="pipeline-section" aria-labelledby="pipeline-title"><div class="pipeline-intro"><p class="eyebrow">THE RESEARCH PIPELINE</p><h2 id="pipeline-title">Images → spatial understanding</h2></div><ol class="pipeline">${[
  ["01", "Multi-view RGB", "Observe"],
  ["02", "SLAM / Camera pose", "Localize"],
  ["03", "Depth / Multi-View Stereo", "Estimate"],
  ["04", "Gaussian Splatting", "Represent"],
  ["05", "3D Reconstruction", "Reconstruct"],
]
  .map(([n, t, s]) => `<li><span>${n} / ${s}</span><h3>${t}</h3></li>`)
  .join("")}</ol></section>`;
const pageHero = (label, title, text) =>
  `<header class="page-hero"><p class="eyebrow">${label}</p><h1>${title}</h1><p>${text}</p></header>`;
const outputs = {
  "index.html": page(
    "index.html",
    profile.role,
    `${profile.name}, Researcher at KETI. ${profile.fields}.`,
    `${hero}${focus}${pipeline}<section id="publications">${sectionHead("02 / SELECTED PUBLICATIONS", "From ideas to published research.", link(["All publications", "publications.html"], "arrow-link"))}<h3 class="group-title">Published / Accepted</h3>${publications
      .filter((p) => p.status === "Published")
      .slice(0, 2)
      .map((p) => publication(p, true))
      .join(
        "",
      )}<div class="review-preview"><div><p class="eyebrow">ONGOING RESEARCH</p><h3>Under Review</h3></div><div>${publications
      .filter((p) => p.status === "Under Review")
      .map(
        (p) =>
          `<a href="publications.html#${p.id}"><strong>${p.id === "m2depth" ? "M2Depth" : "M2SLAM"}</strong><span>${esc(p.venue)}</span><span class="review-note">Under Review · First Author</span><span aria-hidden="true">↗</span></a>`,
      )
      .join(
        "",
      )}</div></div></section><section id="projects">${sectionHead("03 / FEATURED PROJECTS", "Research, out in the world.", link(["All projects", "projects.html"], "arrow-link"))}<div class="project-grid">${projects.map((p) => project(p)).join("")}</div></section>${experienceSection}${educationSection}`,
    '<link rel="modulepreload" href="assets/js/reconstruction.js">',
  ),
  "publications.html": page(
    "publications.html",
    "Publications",
    "Published research and clearly identified manuscripts under review in 3D computer vision.",
    `${pageHero("PUBLICATIONS", "Geometry. Depth. Discovery.", "Research in multi-view stereo, Gaussian Splatting, and dense 3D mapping.")}<div class="page-jumps"><a href="#published">Published / Accepted <span>03</span></a><a href="#under-review">Under Review <span>02</span></a></div><section id="published">${sectionHead("PUBLICATIONS", "Published / Accepted")}<div class="publication-list">${publications
      .filter((p) => p.status === "Published")
      .map((p) => publication(p))
      .join(
        "",
      )}</div></section><section id="under-review">${sectionHead("MANUSCRIPTS", "Under Review", "<p>The following manuscripts are under review<br>and have not been accepted for publication.</p>")}${publications
      .filter((p) => p.status === "Under Review")
      .map((p) => publication(p))
      .join("")}</section>`,
  ),
  "projects.html": page(
    "projects.html",
    "Projects",
    "Research case studies in drone reconstruction, multi-view stereo, and diffusion-assisted geometry completion.",
    `${pageHero("SELECTED PROJECTS", "From pixels to places.", "Building reconstruction pipelines around real capture conditions, from online aerial mapping to geometry completion.")}<section class="project-studies" aria-label="Research case studies">${projects.map((p) => project(p, true)).join("")}</section><section>${sectionHead("EARLIER WORK", "Applied computer vision.")}<div class="industry-list">${industryProjects.map(([o, d, t]) => `<article><p class="eyebrow">${d}</p><h3>${o}</h3><p>${t}</p></article>`).join("")}</div></section>`,
  ),
  "about.html": page(
    "about.html",
    "About",
    "Researcher at KETI. Experience, completed education, professional service, and patent applications.",
    `${pageHero("ABOUT", "A focus on spatial understanding.", "I am Byeong Gwon Lee, a 3D Computer Vision Researcher at KETI. My work connects camera tracking, dense depth estimation, and 3D reconstruction.")}<div class="about-intro">${image("headshot.png", "Portrait of Byeong Gwon Lee", "portrait")}<div><p class="eyebrow">RESEARCH INTERESTS</p><h2>Learned priors.<br>Geometric foundations.</h2><p>I work on online mapping and offline reconstruction, with interests in reliable depth estimation, adaptive view selection, and geometry completion.</p><div class="text-links">${links(profile.links)}</div></div></div>${experienceSection}${educationSection}<section>${sectionHead("ACADEMIC COMMUNITY", "Service & intellectual property.")}<div class="service-grid"><article><p class="eyebrow">PROFESSIONAL SERVICE</p><h3>IEEE Access</h3><p>Peer Reviewer · Nov. 2025 – Present</p></article><article><p class="eyebrow">PATENT APPLICATIONS</p><h3>Online multi-view stereo for 3D modeling</h3><p lang="ko">온라인 다시점 스테레오를 이용한 3차원 모델링 시스템 및 방법</p><p>Korean patent application · Principal inventor</p><p>System and Method for 3D Modeling Using Online Multi-view Stereo</p><p>PCT international patent application · Principal inventor</p></article></div></section><section>${sectionHead("TOOLS & METHODS", "Built around the research.")}<dl class="skills"><div><dt>Geometry & reconstruction</dt><dd>SLAM, Multi-View Stereo, Gaussian Splatting, bundle adjustment, COLMAP, OpenMVS</dd></div><div><dt>Learning & implementation</dt><dd>Python, PyTorch, C/C++, CUDA</dd></div><div><dt>Computer vision</dt><dd>Depth estimation, object detection, image segmentation, few-shot learning</dd></div><div><dt>Research infrastructure</dt><dd>Linux, Git, Docker, Kubernetes</dd></div></dl></section>`,
  ),
  "demo.html": page(
    "demo.html",
    "Research demos",
    "Video demonstrations of MVS-GS and online 3D Gaussian Splatting.",
    `${pageHero("RESEARCH IN MOTION", "Reconstruction, frame by frame.", "Video demonstrations accompanying published work.")}<section class="demo-panel"><h2 id="demo-title">Choose a research demo</h2><p id="demo-message">Select a video to view the reconstruction results.</p><div class="text-links"><a href="demo.html?v=mvsgs">MVS-GS</a><a href="demo.html?v=ijcai">IJCAI 2025</a></div><video id="demo-video" controls playsinline preload="metadata" hidden></video><noscript><p><a href="assets/demo_video/demo_video_mvsgs.mp4">Open MVS-GS video</a> · <a href="assets/demo_video/demo_video_ijcai.mp4">Open IJCAI video</a></p></noscript><div class="demo-overviews"><article><h3>IJCAI 2025 — Visual overview</h3><p id="overview-ijcai">The video shows rendered depth, rendered images, and a 3D Gaussian map, followed by side-by-side views labelled “Ours” and “MVS-GS”. Examples include building exteriors and indoor scenes, with camera markers illustrating novel-view selection.</p></article><article><h3>MVS-GS — Visual overview</h3><p id="overview-mvsgs">The video introduces an RGB-to-3D mapping pipeline: camera-pose estimation, multi-view stereo depth estimation, depth refinement, and Gaussian mapping. It then shows reconstructed aerial building scenes and side-by-side rendering comparisons labelled “Ours” and “Photo-SLAM”.</p></article></div><p><a href="publications.html">← Back to publications</a></p></section>`,
  ),
};
let stale = false;
for (const [file, source] of Object.entries(outputs)) {
  const content = source.replace(/></g, ">\n<");
  if (process.argv.includes("--check")) {
    if ((await readFile(file, "utf8")) !== content) {
      console.error(`Out of date: ${file}`);
      stale = true;
    }
  } else await writeFile(file, content);
}
if (stale) process.exitCode = 1;
else
  console.log(
    process.argv.includes("--check")
      ? "All generated pages are current."
      : "Generated 5 static pages.",
  );
